// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnyknfitlkszbtbmftdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNueWtuZml0bGtzemJ0Ym1mdGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTk1NDUsImV4cCI6MjA2NDc3NTU0NX0.liK6mwbYkyXwDN3tp1QqZMDFYaqi7cxSnbYP1MaqIY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);